/**:
  ros__parameters:
    joint_state_command_topics: ["/swerve/command_joint_states"]
    command_transmit_frequency: 100.0
    parameter_transmit_frequency: 10.0
    rmc_num: 2
    rmc_0:
      motor_num: 8
      feedback_period_ms: 10
      state_period_ms: 100
      timeout_ms: 255
      joint_name: ["swerve_wheel_base_0", "swerve_wheel_base_1", "swerve_wheel_base_2", "swerve_wheel_base_3",
                   "swerve_wheel_0", "swerve_wheel_1", "swerve_wheel_2", "swerve_wheel_3"]
      control_mode: ["position", "position", "position", "position", "speed", "speed", "speed", "speed"]
      ratio: [108.0, 108.0, 108.0, 108.0,
              5.052631578947368, 5.052631578947368, 5.052631578947368, 5.052631578947368]
      origin_get_mode: ["as5600", "as5600", "as5600", "as5600", "manual", "manual", "manual", "manual"]
      origin_target: [0, 0, 0, 0, 0, 0, 0, 0]
      position_offset: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      origin_id: [0, 1, 2, 3, 0, 0, 0, 0] # origin id temp
      max_position: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      min_position: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      speed_kp: [2.0, 2.0, 2.0, 2.0, 1.0, 1.0, 1.0, 1.0]
      speed_ki: [1.8, 1.8, 1.8, 1.8, 0.0, 0.0, 0.0, 0.0]
      speed_kd: [0.1, 0.1, 0.1, 0.1, 0.0, 0.0, 0.0, 0.0]
      position_kp: [500.0, 500.0, 500.0, 500.0, 0.0, 0.0, 0.0, 0.0]
      position_ki: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      position_kd: [10000.0, 10000.0, 10000.0, 10000.0, 0.0, 0.0, 0.0, 0.0]
      stop_speed_threshold: [60, 60, 60, 60, 60, 60, 60, 60]
      stop_time_threshold_ms: [100, 100, 100, 100, 100, 100, 100, 100]
      use_position_limit: [false, false, false, false, false, false, false, false]
    rmc_1:
      motor_num: 2
      feedback_period_ms: 10
      state_period_ms: 100
      timeout_ms: 255
      joint_name: ["collector_arm_left", "collector_arm_right"]
      control_mode: ["position", "position"]
      ratio: [-36.0, 36.0]
      origin_get_mode: ["limit_switch", "limit_switch"]
      origin_target: [1500, -1500]
      position_offset: [0.0, 0.0]
      origin_id: [0, 1]
      max_position: [0.0, 0.0]
      min_position: [0.0, 0.0]
      speed_kp: [2.0, 2.0]
      speed_ki: [1.8, 1.8]
      speed_kd: [0.1, 0.1]
      position_kp: [200.0, 200.0]
      position_ki: [0.0, 0.0]
      position_kd: [100.0, 100.0]
      stop_speed_threshold: [60, 60]
      stop_time_threshold_ms: [100, 100]
      use_position_limit: [false, false]

      vesc_num: 1
      vesc.joint_name: ["belt_launcher"]
      vesc.bus_id: [1]
      vesc.id: [19]

    nidec_num: 1
    nidec_0:
      motor_num: 2
      feedback_period_ms: 10
      state_period_ms: 100
      timeout_ms: 255
      joint_name: ["collector_hand_left", "collector_hand_right"]
      control_mode: ["position", "position"]
      ratio: [1.0, -1.0]
      origin_get_mode: ["stall","stall"]
      origin_target: [50, -50]
      position_offset: [1.57, 1.57]
      origin_id: [0,0]
      max_position: [0.0, 0.0]
      min_position: [0.0, 0.0]
      max_speed: [100, 100]
      position_kp: [2.0, 2.0]
      position_ki: [0.0, 0.0]
      position_kd: [5.0, 5.0]
      stop_speed_threshold: [60, 60]
      stop_time_threshold_ms: [100, 100]
      use_position_limit: [false, false]

    i2c_num: 4
    i2c_0:
      device_type: "as5600"
      period_ms: 10
      joint_name: "swerve_wheel_base_0_as5600"
      as5600:
        zero_position: 1.7486018366025515  # -2.534   * -1.0 - math.pi / 4 
        ratio: -1.0
    i2c_1:
      device_type: "as5600"
      period_ms: 10
      joint_name: "swerve_wheel_base_1_as5600"
      as5600:
        zero_position: -1.5036018366025519  # 2.289 * -1.0 + math.pi / 4
        ratio: -1.0
    i2c_2:
      device_type: "as5600"
      period_ms: 10
      joint_name: "swerve_wheel_base_2_as5600"
      as5600:
        zero_position: 2.835194490192345 # -0.479  * -1.0 + math.pi / 4 * 3 
        ratio: -1.0
    i2c_3:
      device_type: "as5600"
      period_ms: 10
      joint_name: "swerve_wheel_base_3_as5600"
      as5600:
        zero_position: -5.185194490192345 # 2.829   * -1.0 - math.pi / 4 * 3
        ratio: -1.0
