/**:
  ros__parameters:
    num_button: 15
    button_0:
      function: "power"
      mode: "toggle_off"
    button_1:
      function: "power"
      mode: "toggle_on"
    button_2:
      function: "allow_auto_drive"
      mode: "hold"
    button_3:
      function: "joint_position"
      mode: "hold"
      joint_name: "belt_launcher"
      position_on: 0.5
      position_off: 0.0
    button_9:
      function: "joint_position"
      mode: "hold"
      joint_name: "collector_hand_left"
      position_on: 0.0    # ボタン押している間開く　逆だと事故る
      position_off: 1.75
    button_10:
      function: "joint_position"
      mode: "hold"
      joint_name: "collector_hand_right"
      position_on: 0.0
      position_off: 1.75
    button_11:
      function: "get_origin"
      mode: "click"
      joint_name: "collector_hand_left"
    button_12:
      function: "get_origin"
      mode: "click"
      joint_name: "collector_hand_right"
    zl:
      function: "joint_position"
      mode: "hold"
      joint_name: "collector_arm_left"
      position_on: 2.0
      position_off: 0.0
    zr:
      function: "joint_position"
      mode: "hold"
      joint_name: "collector_arm_right"
      position_on: 2.0
      position_off: 0.0