/**:
  ros__parameters:
    num_button: 15
    button_0:
      function: "power"
      mode: "toggle_off"
    button_1:
      function: "power"
      mode: "toggle_on"
    button_2:
      function: "allow_auto_drive"
      mode: "toggle"
    button_3:
      function: "joint_speed"
      mode: "hold"
      joint_name: "belt_launcher"
      speed_on: 1800.0
      speed_off: 0.0
    button_9:
      function: "joint_position"
      mode: "hold"
      joint_name: "collector_hand_left"
      position_on: 1.7    # ボタン押している間開く　逆だと事故る
      position_off: 0.2
    button_10:
      function: "joint_position"
      mode: "hold"
      joint_name: "collector_hand_right"
      position_on: 1.7
      position_off: 0.2
    button_11:
      function: "get_origin"
      mode: "positive_edge"
      joint_names: ["helper"]
    button_12:
      function: "joint_position"
      mode: "hold"
      joint_name: "helper"
      position_on  : 1.7
      position_off : 0.0 
    button_13:
      function: "get_origin"
      mode: "positive_edge"
      joint_names: ["collector_arm_left", "collector_arm_right"]
    button_14:
      function: "get_origin"
      mode: "positive_edge"
      joint_names: ["collector_hand_left", "collector_hand_right"]
    zl:
      function: "joint_position"
      mode: "hold"
      joint_name: "collector_arm_left"
      position_on: 1.7
      position_off: 0.0
    zr:
      function: "joint_position"
      mode: "hold"
      joint_name: "collector_arm_right"
      position_on: 1.7
      position_off: 0.0