/**:
  ros__parameters:
    joint_state_rule:
      rule_0:
        if_0:
          joint_name: "collector_arm_left"
          range: [0.01, 1.5]
        then:
          joint_name: "collector_hand_left"
          range: [1.75, 1.75]
      rule_1:
        if_0:
          joint_name: "collector_arm_right"
          range: [0.01, 1.5]
        then:
          joint_name: "collector_hand_right"
          range: [1.75, 1.75]
          